Repository ConceptBe/conceptbe-frontend, pull requests merged in 2024-03, with the labels that each got.

#59 Feat/#58: 게시글 수정 기능
  src/App.tsx
  src/layouts/Navbar.tsx
  src/pages/Write/components/TeamRecruitmentSection.tsx
  src/pages/WriteEdit/WriteEdit.page.tsx
  src/pages/WriteEdit/components/Header.tsx
  src/pages/WriteEdit/components/RecruitmentPlaceSection.tsx
  src/pages/WriteEdit/components/TitleAndIntroduceSection.tsx
  src/pages/WriteEdit/hooks/mutations/usePutIdea.ts
  src/pages/WriteEdit/hooks/queries/useIdeaDetailQuery.ts
  src/pages/WriteEdit/hooks/queries/useWritingInfoQuery.ts
  src/pages/WriteEdit/types/index.ts
  src/pages/WriteEdit/utils/get2DepthCountsBy1Depth.ts
  src/pages/components/NewIdeaCard/compound/Content/Content.tsx
  src/pages/components/NewIdeaCard/compound/Content/ContentEditDropdown.tsx
  src/router.tsx
Labels: feat

#60 Feat/#43: 프로필 수정 기능을 구현
  src/layouts/Navbar.tsx
  src/pages/Login/KakaoRedirect.tsx
  src/pages/Profile/Setting.page.tsx
  src/pages/Profile/components/ProfileInfoSection.tsx
  src/pages/Profile/types/index.ts
  src/pages/ProfileEdit/ProfileEdit.page.tsx
  src/pages/ProfileEdit/hooks/useProfileQuery.ts
  src/pages/ProfileEdit/hooks/usePutProfileMutation.ts
  src/pages/ProfileEdit/service/convertProfileQuery.ts
  src/pages/ProfileEdit/types/index.ts
  src/pages/SignUp/hooks/useCheckDuplicateNickname.ts
  src/pages/SignUp/hooks/useSetDetailSkills.ts
  src/pages/Temp.tsx
  src/router.tsx
Labels: feat

#61 Feat/#55: 상대, 내 프로필 조건부 렌더링, 게시글 삭제 기능 추가
  src/layouts/Back.tsx
  src/layouts/Navbar.tsx
  src/pages/Feed/components/NewIdeaCardListSection/NewIdeaCardListSection.tsx
  src/pages/Feed/hooks/mutations/useDeleteBookmarkIdea.ts
  src/pages/Feed/types/index.ts
  src/pages/FeedDetail/components/Comment.tsx
  src/pages/FeedDetail/components/Comments.tsx
  src/pages/Profile/Profile.page.tsx
  src/pages/Profile/components/MyProfile/BookmarkSection.tsx
  src/pages/Profile/components/MyProfile/IdeaSection.tsx
  src/pages/Profile/components/MyProfile/MyProfile.page.tsx
  src/pages/Profile/components/OtherProfile/BookmarkSection.tsx
  src/pages/Profile/components/OtherProfile/Header.tsx
  src/pages/Profile/components/OtherProfile/IdeaSection.tsx
  src/pages/Profile/components/OtherProfile/OtherProfile.page.tsx
  src/pages/Profile/components/ProfileInfoSection.tsx
  src/pages/Profile/hooks/queries/useBookmarkedIdeasQuery.ts
  src/pages/Profile/hooks/queries/useIdeasQuery.ts
  src/pages/Profile/hooks/queries/useMemberInfoQuery.ts
  src/pages/Profile/types/index.ts
  src/pages/Profile/utils/getUserId.ts
  src/pages/Profile/utils/memberId.ts
  src/pages/ProfileEdit/ProfileEdit.page.tsx
  src/pages/ProfileEdit/hooks/usePutProfileMutation.ts
  src/pages/components/NewIdeaCard/compound/Content/Content.tsx
  src/pages/components/NewIdeaCard/compound/Content/ContentEditDropdown.tsx
  src/pages/components/NewIdeaCard/compound/Profile/Profile.tsx
  src/pages/components/NewIdeaCard/hooks/mutations/useDeleteIdea.ts
  src/pages/hooks/useNavigatePage.ts
  src/router.tsx
Labels: feat, refactor

#56 Feat/#54: Alert, Confirm 컴포넌트 구현 및 ErrorBoundary 적용
  package-lock.json
  package.json
  src/App.tsx
  src/components/ErrorBoundary/ApiErrorBoundary.tsx
  src/components/ErrorBoundary/ErrorFallback.tsx
  src/components/ErrorBoundary/GlobalErrorBoundary.tsx
  src/components/Modal/Alert.tsx
  src/components/Modal/Confirm.tsx
  src/components/Modal/Modal.tsx
  src/hooks/useAlert.tsx
  src/hooks/useConfrim.tsx
  src/main.tsx
  src/pages/NotFound.tsx
  src/pages/SignUp/SignUp.page.tsx
  src/pages/SignUp/hooks/useSignUpMutation.ts
  src/router.tsx
  yarn.lock
Labels: feat

#44 Feat/#38: SEO 최적화 및 메타 태그 적용
  index.html
  package-lock.json
  package.json
  public/_redirects
  public/assets/conceptbe_og_image.png
  public/assets/favicon.png
  public/vite.svg
  src/components/SEOMeta/SEOMeta.tsx
  src/main.tsx
  src/pages/Feed/Feed.page.tsx
  src/pages/FeedDetail/FeedDetail.page.tsx
  src/pages/Login/Agreement.tsx
  src/pages/Login/Login.tsx
  src/pages/Profile/More.page.tsx
  src/pages/Profile/Profile.page.tsx
  src/pages/SignUp/SignUp.page.tsx
  src/pages/Write/Write.page.tsx
  yarn.lock
Labels: feat

#66 Refactor/#65: MobileView 375px에서 420px로 확장
  index.html
  package-lock.json
  package.json
  src/components/ErrorBoundary/ErrorFallback.tsx
  src/components/ProfileInfo.tsx
  src/constants/index.ts
  src/layouts/Back.tsx
  src/layouts/MobileView.tsx
  src/layouts/Navbar.tsx
  src/pages/Feed/Feed.page.tsx
  src/pages/Feed/components/BestIdeaCard/BestIdeaCard.tsx
  src/pages/Feed/components/BestIdeaCardListSection/BestIdeaCardListSection.tsx
  src/pages/Feed/components/NewIdeaCardListSection/NewIdeaCardListSection.tsx
  src/pages/FeedDetail/components/Comment.tsx
  src/pages/FeedDetail/components/CommentProfileInfo.tsx
  src/pages/FeedDetail/components/ModifyDropdown.tsx
  src/pages/FeedDetail/components/Recomment.tsx
  src/pages/FeedDetail/components/WriteCommentProfileInfo.tsx
  src/pages/FeedDetail/types/index.ts
  src/pages/Login/Agreement.tsx
  src/pages/Profile/asset/book-open.svg
  src/pages/Profile/asset/index.ts
  src/pages/Profile/asset/message-dots-circle.svg
  src/pages/Profile/asset/profile-image-default.svg
  src/pages/Profile/components/EmptyTabContentSection.tsx
  src/pages/Profile/components/MyProfile/BookmarkSection.tsx
  src/pages/Profile/components/MyProfile/IdeaSection.tsx
  src/pages/Profile/components/MyProfile/MyProfile.page.tsx
  src/pages/Profile/components/OtherProfile/BookmarkSection.tsx
  src/pages/Profile/components/OtherProfile/IdeaSection.tsx
  src/pages/Profile/components/OtherProfile/OtherProfile.page.tsx
  src/pages/Profile/components/ProfileInfoSection.tsx
  src/pages/ProfileEdit/ProfileEdit.page.tsx
  src/pages/SignUp/SignUp.page.tsx
  src/pages/SignUp/hooks/useValidateUserInfo.ts
  src/pages/Write/Write.page.tsx
  src/pages/Write/components/Header.tsx
  src/pages/WriteEdit/WriteEdit.page.tsx
  src/pages/components/NewIdeaCard/NewIdeaCard.tsx
  src/pages/components/NewIdeaCard/assets/more24.svg
  src/pages/components/NewIdeaCard/assets/pencil16.svg
  src/pages/components/NewIdeaCard/assets/x16.svg
  src/pages/components/NewIdeaCard/compound/Content/Content.tsx
  src/pages/components/NewIdeaCard/compound/Content/ContentEditDropdown.tsx
  src/pages/components/NewIdeaCard/compound/Profile/Profile.tsx
  yarn.lock
Labels: feat, refactor

#69 Refactor/#67: 댓글 및 대댓글 스크롤 오류 수정
  index.html
  src/layouts/MobileView.tsx
  src/layouts/contexts/MobileViewContext.tsx
  src/pages/FeedDetail/contexts/CommentFocusContext.tsx
Labels: fix

#71 Hotfix: MobileView 내 불필요한 Container 컴포넌트 제거 및 CSS 속성 단순화
  src/layouts/MobileView.tsx
  src/layouts/contexts/MobileViewContext.tsx
  src/pages/FeedDetail/contexts/CommentFocusContext.tsx
Labels: fix

#72 Hotfix: scroll behavior를 auto로 변경
  src/pages/FeedDetail/contexts/CommentFocusContext.tsx
Labels: fix

#73 Hotfix: ios, android 키보드 open 동작 방식 차이에 따른 보정 로직 추가
  src/pages/FeedDetail/contexts/CommentFocusContext.tsx
Labels: fix

#74 Hotfix: visualViewPortHeight 값을 스크롤 이후에도 초기값으로 고정
  src/pages/FeedDetail/contexts/CommentFocusContext.tsx
Labels: fix

#75 Hotfix: visualViewPortHeight 에서 innerHeight 값으로 고정토록 변경
  src/pages/FeedDetail/contexts/CommentFocusContext.tsx
Labels: fix

#76 Hotfix: onresize 이벤트 등록을 루트에서 한 번으로 수행 및 scroll behavior 방식 smooth로 재 변경
  src/layouts/MobileView.tsx
  src/pages/FeedDetail/contexts/CommentFocusContext.tsx
Labels: fix

#77 Hotfix: 문제 확인을 위한 스크롤 로직 잠시 보류
  src/layouts/MobileView.tsx
  src/pages/FeedDetail/contexts/CommentFocusContext.tsx
Labels: fix

#78 Hotfix/comment#8: 댓글 및 대댓글 입력 시 하단에 여백이 생기는 오류 수정
  package-lock.json
  package.json
  src/layouts/MobileView.tsx
  src/pages/FeedDetail/contexts/CommentFocusContext.tsx
  src/styles/globalStyles.ts
  src/styles/reset.css
  yarn.lock
Labels: fix

#79 Hotfix: (대)댓글 입력창이 키패드에 의해 가려질 경우만 판단하여 스크롤 상단으로 끌어올리도록 변경
  src/pages/FeedDetail/contexts/CommentFocusContext.tsx
Labels: fix

#80 Hotfix: 댓글 및 대댓글 하단 공백 오류 수정
  src/pages/FeedDetail/contexts/CommentFocusContext.tsx
Labels: fix

#82 Refactor/#81: UI 및 디자인 시스템 관련 오류 및 필터링 초기화 버튼 수정
  package-lock.json
  package.json
  src/components/ErrorBoundary/ErrorFallback.tsx
  src/pages/Feed/Feed.page.tsx
  src/pages/Feed/components/FilterBottomSheet/FilterBottomSheet.tsx
  src/pages/FeedDetail/components/EditComment.tsx
  src/pages/FeedDetail/components/WriteComment.tsx
  src/pages/FeedDetail/components/WriteRecomment.tsx
  src/pages/Profile/components/MyProfile/BookmarkSection.tsx
  src/pages/ProfileEdit/ProfileEdit.page.tsx
  src/pages/components/NewIdeaCard/NewIdeaCard.tsx
  src/pages/components/NewIdeaCard/compound/Profile/Profile.tsx
  src/styles/globalStyles.ts
  yarn.lock
Labels: fix

#84 Feat/#83: 페이지 이동 시 스크롤 위치 초기화 | 뒤로가기는 이전 스크롤 위치 유지
  src/App.tsx
  src/hooks/useInitScrollPosition.ts
  src/hooks/useRouteMatch.ts
  src/pages/Feed/Feed.page.tsx
  src/pages/FeedDetail/FeedDetail.page.tsx
  src/pages/Profile/Profile.page.tsx
  src/pages/ProfileEdit/ProfileEdit.page.tsx
  src/pages/SignUp/SignUp.page.tsx
  src/pages/Write/Write.page.tsx
  src/pages/WriteEdit/WriteEdit.page.tsx
Labels: feat
